server:
  port: 2020

spring:
  application:
    name: USER-SERVICE-API
  datasource:
    hikari:
      maximum-pool-size: 1
    url: jdbc:postgresql://localhost:5432/UserDbServie
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
    hibernate:
      ddl-auto: update